name: Build test
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v2

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build du projet C++/CLR
      run: msbuild RetroTME.sln /p:Configuration=Release

    - name: Afficher le statut
      run: echo "Build terminé !"

