name: Build C++/CLR with .NET
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v2

    - name: Installer le SDK .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'  # Version souhaitée

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build du projet C++/CLR
      run: msbuild RetroTME.sln /p:Configuration=Release

    - name: Archiver les fichiers générés pour Release
      uses: actions/upload-artifact@v2
      with:
        name: release-artifacts
        path: x64\Release\  # Chemin vers les fichiers générés pour la configuration Release

    - name: Afficher le statut
      run: echo "Build terminé !"

